import 'dart:convert';

import 'package:archive/archive.dart';

import '../models/design_system.dart' as models;
import 'token_engine.dart';

/// Generates a complete design system package (zip) with:
/// design-system/
///   tokens/
///   theme/
///   components/
///   documentation/
class PackageGeneratorService {
  /// Build zip bytes for the design system package.
  static List<int> buildPackage(models.DesignSystem ds) {
    final archive = Archive();
    final prefix = _sanitizeDirName(ds.name);

    // 1) tokens/tokens.json — single source of truth
    final tokenMap = TokenEngine.buildTokenMap(ds);
    archive.addFile(ArchiveFile.bytes(
      '$prefix/tokens/tokens.json',
      utf8.encode(const JsonEncoder.withIndent('  ').convert(tokenMap)),
    ));

    // 2) theme/ — platform-specific theme files (samples)
    final flutterTheme = _generateFlutterThemeFromTokens(ds, tokenMap);
    archive.addFile(ArchiveFile.bytes('$prefix/theme/flutter_theme.dart', utf8.encode(flutterTheme)));
    final cssVars = _generateCssVariables(tokenMap);
    archive.addFile(ArchiveFile.bytes('$prefix/theme/variables.css', utf8.encode(cssVars)));

    // 3) components/ — component definitions (JSON)
    final componentsJson = {
      'buttons': ds.components.buttons,
      'cards': ds.components.cards,
      'inputs': ds.components.inputs,
      'navigation': ds.components.navigation,
      'avatars': ds.components.avatars,
    };
    archive.addFile(ArchiveFile.bytes(
      '$prefix/components/components.json',
      utf8.encode(const JsonEncoder.withIndent('  ').convert(componentsJson)),
    ));

    // 4) documentation/ — README with token reference
    final readme = _generateDocumentation(ds, tokenMap);
    archive.addFile(ArchiveFile.bytes('$prefix/documentation/README.md', utf8.encode(readme)));

    // 5) Root README
    final rootReadme = '''# ${ds.name}

${ds.description.isEmpty ? 'Design system package.' : ds.description}

## Structure

- **tokens/** — Design tokens (single source of truth). Use \`tokens.json\` in your pipeline.
- **theme/** — Platform-specific theme files (Flutter, CSS). Regenerate from tokens as needed.
- **components/** — Component definitions and metadata.
- **documentation/** — Token reference and usage.

## Version

${ds.version}

## Install / Use

1. Copy \`tokens/tokens.json\` into your project or CI.
2. Use \`theme/\` files as a starting point for your app theme.
3. Keep \`components/\` in sync with your UI library.

---
Generated by Design System Builder.
''';
    archive.addFile(ArchiveFile.bytes('$prefix/README.md', utf8.encode(rootReadme)));

    return ZipEncoder().encode(archive) ?? [];
  }

  static String _sanitizeDirName(String name) {
    return name
        .replaceAll(RegExp(r'[<>:"/\\|?*]'), '_')
        .replaceAll(' ', '-')
        .toLowerCase();
  }

  static String _generateFlutterThemeFromTokens(models.DesignSystem ds, Map<String, dynamic> tokens) {
    final b = StringBuffer();
    b.writeln("// Flutter theme generated from design tokens.");
    b.writeln("// Single source of truth: tokens/tokens.json");
    b.writeln("import 'package:flutter/material.dart';");
    b.writeln();
    b.writeln("class AppTheme {");
    b.writeln("  static ThemeData get theme => ThemeData(");
    b.writeln("    useMaterial3: true,");
    final primary = tokens['color.primary.500'] ?? tokens['color.primary.primary'] ?? '#3B82F6';
    final hex = primary is String ? primary.replaceAll('#', '') : '3B82F6';
    b.writeln("    colorScheme: ColorScheme.fromSeed(seedColor: Color(0xFF$hex)),");
    b.writeln("  );");
    b.writeln("}");
    return b.toString();
  }

  static String _generateCssVariables(Map<String, dynamic> tokens) {
    final b = StringBuffer();
    b.writeln("/* CSS variables from design tokens */");
    b.writeln(":root {");
    for (final e in tokens.entries) {
      if (e.value is! Map && e.value != null) {
        final key = '--${e.key.replaceAll('.', '-')}';
        b.writeln("  $key: ${e.value};");
      }
    }
    b.writeln("}");
    return b.toString();
  }

  static String _generateDocumentation(models.DesignSystem ds, Map<String, dynamic> tokenMap) {
    final b = StringBuffer();
    b.writeln("# Token reference — ${ds.name}");
    b.writeln();
    b.writeln("| Token | Value |");
    b.writeln("|-------|-------|");
    for (final e in tokenMap.entries) {
      if (e.value is! Map) {
        b.writeln("| \`${e.key}\` | ${e.value} |");
      }
    }
    return b.toString();
  }
}
