// File generated by FlutterFire CLI.
// This file will be auto-generated when you run: flutterfire configure
// For now, this is a template. You need to run the FlutterFire CLI to generate the actual config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArHWRq0Ehu7PIaWvthITcHgEhWUw8V6pw',
    appId: '1:47033728900:web:2b513c3e6096e86e95a7d1',
    messagingSenderId: '47033728900',
    projectId: 'my-flutter-apps-f87ea',
    authDomain: 'my-flutter-apps-f87ea.firebaseapp.com',
    storageBucket: 'my-flutter-apps-f87ea.firebasestorage.app',
    measurementId: 'G-ZS7ZPLDRB8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI62HRYjVqWhPSrUhpKhDuw_MW8ISNe2A',
    appId: '1:47033728900:ios:7a9b609fa9a75ffb95a7d1',
    messagingSenderId: '47033728900',
    projectId: 'my-flutter-apps-f87ea',
    storageBucket: 'my-flutter-apps-f87ea.firebasestorage.app',
    iosClientId: '47033728900-b5rmrek7q4tsh8n6aqivu2s6cjr7kdvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.designSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArHWRq0Ehu7PIaWvthITcHgEhWUw8V6pw',
    appId: '1:47033728900:web:72141861e787f83595a7d1',
    messagingSenderId: '47033728900',
    projectId: 'my-flutter-apps-f87ea',
    authDomain: 'my-flutter-apps-f87ea.firebaseapp.com',
    storageBucket: 'my-flutter-apps-f87ea.firebasestorage.app',
    measurementId: 'G-NXZ70LSNNF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI62HRYjVqWhPSrUhpKhDuw_MW8ISNe2A',
    appId: '1:47033728900:ios:7a9b609fa9a75ffb95a7d1',
    messagingSenderId: '47033728900',
    projectId: 'my-flutter-apps-f87ea',
    storageBucket: 'my-flutter-apps-f87ea.firebasestorage.app',
    iosClientId: '47033728900-b5rmrek7q4tsh8n6aqivu2s6cjr7kdvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.designSystem',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxkBlBXCSUSn5j_mJEaiLrF2fS5Xx8xQ4',
    appId: '1:47033728900:android:56cfe85c9f6b1b3495a7d1',
    messagingSenderId: '47033728900',
    projectId: 'my-flutter-apps-f87ea',
    storageBucket: 'my-flutter-apps-f87ea.firebasestorage.app',
  );

}